#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "vpn_client_core.h" // Include our Rust library header

// Forward declare the UI class generated by Qt's UIC.
QT_BEGIN_NAMESPACE
namespace Ui
{
    class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    // Slot to handle the connect button click.
    void onConnectButtonClicked();

private:
    // Pointer to the UI elements.
    Ui::MainWindow *ui;

    // Pointer to our Rust VPN client instance.
    VpnClient *vpnClient;

    // State variable to track connection status.
    bool isConnected;
};
#endif // MAINWINDOW_H
