#include "mainwindow.h"
// This header is generated by Qt's build system from mainwindow.ui
#include "ui_mainwindow.h"

#include <QMessageBox>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow), vpnClient(nullptr), isConnected(false)
{
    ui->setupUi(this);

    // Create the Rust client instance when the window is created.
    vpnClient = vpn_client_create();
    if (!vpnClient)
    {
        QMessageBox::critical(this, "Error", "Failed to initialize VPN client core.");
        // Disable the button if the core library failed to load.
        ui->connectButton->setEnabled(false);
    }

    // Connect the button's clicked signal to our handler slot.
    connect(ui->connectButton, &QPushButton::clicked, this, &MainWindow::onConnectButtonClicked);
}

MainWindow::~MainWindow()
{
    // Clean up the Rust client instance when the window is closed.
    if (vpnClient)
    {
        if (isConnected)
        {
            vpn_client_disconnect(vpnClient);
        }
        vpn_client_destroy(vpnClient);
    }
    delete ui;
}

void MainWindow::onConnectButtonClicked()
{
    if (!isConnected)
    {
        // --- Hardcoded values for testing ---
        // In a real app, these would come from the Go API and user input.
        const char *clientPrivateKey = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="; // Placeholder
        const char *clientIp = "10.10.10.2/32";
        const char *serverPublicKey = "j0DFrbaPJWJK5bIU6nZ6bslNgp09e14a0bpvPiE4KF8="; // The public key from your Rust server
        const char *serverEndpoint = "127.0.0.1:51820";                               // Your server's public IP

        if (vpn_client_connect(vpnClient, clientPrivateKey, clientIp, serverPublicKey, serverEndpoint) == 0)
        {
            ui->statusLabel->setText("Status: Connected");
            ui->connectButton->setText("Disconnect");
            isConnected = true;
        }
        else
        {
            QMessageBox::warning(this, "Connection Failed", "Could not connect to the VPN server.");
        }
    }
    else
    {
        if (vpn_client_disconnect(vpnClient) == 0)
        {
            ui->statusLabel->setText("Status: Disconnected");
            ui->connectButton->setText("Connect");
            isConnected = false;
        }
        else
        {
            QMessageBox::warning(this, "Disconnection Failed", "Could not disconnect from the VPN server.");
        }
    }
}
