#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QJsonObject>
#include <QJsonDocument>

#include "vpn_client_core.h" // Include our Rust library header

// Forward declare the UI class generated by Qt's UIC.
QT_BEGIN_NAMESPACE
namespace Ui
{
    class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    // Slot to handle the connect button click.
    void onConnectButtonClicked();
    void onLoginButtonClicked();
    // ADD THESE
    void onRegisterDeviceButtonClicked();
    void onDeviceReplyFinished(QNetworkReply *reply);
    void onLoginReplyFinished(QNetworkReply *reply);
    void onConfigReplyFinished(QNetworkReply *reply);

private:
    // Pointer to the UI elements.
    Ui::MainWindow *ui;

    // Pointer to our Rust VPN client instance.
    VpnClient *vpnClient;

    // State variable to track connection status.
    bool isConnected;

    QNetworkAccessManager *networkManager;
    QString jwtToken;

    struct VpnConfig
    {
        QString clientPrivateKey;
        QString clientIp;
        QString dnsServer;
        QString serverPublicKey;
        QString serverEndpoint;
    } vpnConfig;
};
#endif // MAINWINDOW_H